#Site Info
name: "iamnotaninvestor"
description: "Tales of a novice day trader"
keywords: "day trading, momentum trading, day trader, momentum trader, momo trader"
author: "iamnotaninvestor"


url: "http://www.iamnotaninvestor.com"
baseurl: ""

markdown: kramdown
permalink: :year/:month/:title.html
highlighter: rouge
pygments: true

# Google Analytics
ga_domain: iamnotaninvestor.com
ga_tracking_id: UA-51767912-1

gems:
- jekyll-sitemap
